#!/bin/bash

bootcd_conf=`hostname`.conf
bootcd_conf_nfs=`hostname`.nfsconf
overlay_img=/plc/root/usr/share/bootcd/build/isofs/overlay.img
tftpserver="172.16.3.101"
myplc="myplc-0.4-3.planetlab.i386.rpm"
ipaddr=192.168.0.253

setenforce 0
service iptables stop
chkconfig iptables off

rpm -i $myplc
install -m 755 tftp $HOME/bin/tftp

service plc mount

perl plc_config_xml_gen.pl -i $ipaddr

mkdir -p /plc/root/data/etc/planetlab/configs/
cp plc_config.xml /plc/root/data/etc/planetlab/plc_config.xml
cp site.xml /plc/root/data/etc/planetlab/configs/

service plc start

tar -xzf plcmdline.tar.gz
make -C plcmdline
ln -sf plcmdline/plcsh $HOME/bin/plcsh

mkdir -p /tmp/pl_autoconf/

mv /etc/resolv.conf /etc/resolv.conf.orz

echo "
;  generated by plc_autoconf
search si.star-bed.net
nameserver 127.0.0.1
nameserver 172.16.3.101
" > /etc/resolv.conf

echo "default planet
prompt 0
label planet
	kernel pl_kernel
	APPEND ramdisk_size=100589 initrd=nanodayo@jaist.ac.jp/starbed.img,nanodayo@jaist.ac.jp/`hostname`.img root=/dev/ram0 rw
" > /tmp/pl_autoconf/$bootcd_conf

#echo "default planet
#prompt 0
#label planet
#	kernel pl_nfskernel
#	APPEND ramdisk_size=100589 initrd=nanodayo@jaist.ac.jp/nfs.img,nanodayo@jaist.ac.jp/`hostname`.img root=/dev/ram0 nfsroot=$nfsserver:/planetlab/`hostname` rw
#" > /tmp/pl_autoconf/$bootcd_conf_nfs

echo "
# Add by script
TOTAL_MINIMUM_DISK_SIZE=10
MINIMUM_MEMORY=127000
" >> /plc/root/usr/share/bootmanager/source/configuration

tftp $tftpserver -c put $overlay_img nanodayo@jaist.ac.jp/`hostname`.img
tftp $tftpserver -c put /tmp/pl_autoconf/$bootcd_conf nanodayo@jaist.ac.jp/pxelinux.cfg/$bootcd_conf
#tftp $tftpserver -c put /tmp/pl_autoconf/$bootcd_conf_nfs nanodayo@jaist.ac.jp/pxelinux.cfg/$bootcd_conf_nfs
